### ISSUE TITLE
Legacy Commands

### ISSUE THREAD

**Issue by MeikelLP** [MeikelLP/quantum-core-x#100]
- [x] /level
- [x] /user
- [x] /a #139 
- [x] /purge [all] #239 
- [x] /m /mob #239 
- [x] /ma (depends on #242)
- [x] /mc (depends on #242)
- [x] /mm #239 
- [x] /mob_ld #239 
- [x] /group #239 
- [x] /grrandom #239 
- [x] /goto
- [x] /item #112 
- [x] /kill #233 
- [x] /dc [Target] /kick [Taraget]  #239 
- [x] /ip /ipurge #239 
- [x] /r /reset #239 
- [x] /set [Target] gold [Value] #236 
- [x] /set [Target] exp [Value] #236 
- [x] /set_maxhp [Value] #236 
- [x] /set_maxsp [Value] #236 
- [x] /setskillother #236 
- [x] /setskill /setskillpoint #236 
- [x] /all_skills_master #236 
- [x] /con+ #236 
- [x] /int+ #236 
- [x] /str+ #236 
- [x] /dex+ #236 
- [x] /mspd #236 
- [x] /stat_reset #236 
- [x] /full_set #236 
- [x] /weak /weaken #239 
- [x] /makeguild #239 
- [x] /deleteguild #239 
- [x] /gstate #239 
- [x] /who #239 
- [x] /state #239 
- [x] /pull /pull_monster #239 
- [x] /forgetme #239 
- [x] /aggregate #239 
- [x] /attract_ranger (depends on #238)
