### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by MeikelLP** [MeikelLP/quantum-core-x#98]
As of right now Quantum Core X is not really usable to any degree. In order to become a valid alternative to the original app we have to implement multiple features. These features are going to be listed below grouped by their milestone. Most important or base features first.

## `v0.1` The Baseline

Goal: Most basic working example of a Metin2 server. Includes many commands for testing

- [x] Login
- [x] Character Creation
- [x] Player
  - [ ] Max Level
- [ ] Drops #35
  - [ ] Load drops from config
- [ ] Guilds #12
  - [ ] Join Guilds
  - [ ] Leave Guilds
  - [ ] Create Guilds
- [ ] NPC Shops #82 
  - [ ] Load NPC shops from config
  - [ ] Buy/Sell with NPC shops
- [x] Empire #7 
- [ ] Skills
- [ ] Mobs
  - [ ] Spawn mobs according to config
  - [x] Show level
- [x] Legacy Commands
  - [ ] /level /advance
  - [ ] /user
  - [ ] /a
  - [ ] /purge
  - [ ] /purge all
  - [ ] /m /mob /ma /mc /mm
  - [ ] /group
  - [ ] /grrandom
  - [ ] /transfer
  - [ ] /warp
  - [ ] /goto
  - [ ] /item
  - [ ] /kill
  - [ ] /dc
  - [ ] /ip /ipurge
  - [ ] /r
  - [ ] /set X gold
  - [ ] /set X exp
  - [ ] /set X max_hp
  - [ ] /set X max_sp
  - [ ] /mspd
  - [ ] /set_maxhp
  - [ ] /set_maxsp
  - [ ] /weak /weaken
  - [ ] /setskillother
  - [ ] /setskill /setskillpoint
  - [ ] /shutdown
  - [ ] /makeguild
  - [ ] /deleteguild
  - [ ] /gstate
  - [ ] /who
  - [ ] /stat_reset
  - [ ] /state
  - [ ] /pull /pull_monster
  - [ ] /forgetme
  - [ ] /aggregate
  - [ ] /attract_ranger
  - [ ] /con+
  - [ ] /int+
  - [ ] /str+
  - [ ] /dex+
  - [ ] /full_set
  - [ ] /all_skills_master

## `v0.2` Morphin' and Horsin'

Goal: Add more basic features

- [ ] Change empire by item
- [ ] Passive Skills
- [ ] Emotions System
- [ ] Polymorphing
- [ ] Horses
- [ ] Skill Books
- [ ] Legacy Commands 2
  - [ ] /poly /polymorph
  - [ ] /n /notice
  - [ ] /notice_map
  - [ ] /b
  - [ ] /horse_summon
  - [ ] /horse_level 
  - [ ] /horse_state
  - [ ] /horse_ride
  - [ ] /horse_summon
  - [ ] /horse_unsummon
  - [ ] /horse_set_stat
  - [ ] /user_horse_ride
  - [ ] /user_horse_back
  - [ ] /user_horse_feed
  - [ ] /x
  - [ ] /set X align /set X aligment
  - [ ] /polyitem
  - [ ] /book
  - [ ] /socketitem
  - [ ] /change_attr
  - [ ] /add_attr
  - [ ] /add_socket
  - [ ] /close_shop
  - [ ] /stun
  - [ ] /slow

## `v0.3` Social Update

Goal: Implement more inter-player features

- [ ] Broadcast message - maintenance message/announcement
- [ ] Player duels
- [ ] Player shops
- [ ] Warehouse system
- [ ] Friends
- [ ] Game Masters
- [ ] Groups / Parties
- [ ] Guild Lands
- [ ] Alignments / Ranks
- [ ] Legacy Commands 3
  - [ ] /kiss /slap /french_kiss /clap /cheer1 /cheer2 /dance1-5 /congratulation /forgive /angry /attractive /sad /shy /cheerup /banter /joy
  - [ ] /block_chat
  - [ ] /block_chat_list
  - [ ] /reload u,p,s,q,f,a,c
  - [ ] /eclipse
  - [ ] /xmas_snow
  - [ ] /ungroup
  - [ ] /build
  - [ ] /in /invisible

## `v0.4` Quests

Goal: Implement quests and similar. For example resetting skills is also a quest

- [ ] Quests
   - [ ] Gameplay legacy lua Quests loader
- [ ] Reset Skill Group
- [ ] Legacy Commands 4
  - [ ] /getqf
  - [ ] /setqf
  - [ ] /delqf

## `v0.5` Mounts & Pets

Goal: More player customization by adding mounts and pets

- [ ] Pets
- [ ] Mounts

## `v1.0` The Rock 2

Goal: Production ready instance. Some features may be still missing but an old school game should be possible. At this point no more breaking changes until 2.0.

- [ ] Dungeons
  - [ ] DT
  - [ ] Dragon
- [ ] Change channel System

## Milestone X - other

Some suggestions are by #1 

- [ ] Evolutions up to Beta
- [ ] Automatic Events Calendar & Event Manager System
   - [ ] Clear Moon Event
   - [ ] Football Event
   - [ ] Costume Event
   - [ ] Event Hexagonal Chests
   - [ ] Special Event (where depending on the period you can put another event, eg: Christmas, Summer, Halloween, Easter, etc.)
   - [ ]  OX System
      - [ ] Block Skills in OX Event
- [ ] Biologist research
- [ ] Store/Shop
   - [ ] Item sorting
- [ ] block clients with screen set to smaller than 800x600 (M2Bob hacks)
- [ ] System 4 inventories + keys
- [ ] System Quest Renewal
- [ ] Cube Renewal System
- [ ] Drop Renewal System
- [ ] 6th, 7th & 8th skill
- [ ] Costumes System
   - [ ] Costume Weapon System
      - [ ] Weapon Glow
   - [ ] Mount Suits System
- [ ] Bonuses Page
- [ ] Guild wars
- [ ] Legacy Commands Misc
  - [ ] /gwlist
  - [ ] /gwstop
  - [ ] /gwcancel
  - [ ] /siege
  - [ ] /threeway_info
  - [ ] /threeway_myinfo
  - [ ] /show_arena_list
  - [ ] /end_all_duel
  - [ ] /end_duel
  - [ ] /reset_subskill
  - [ ] /reset
  - [ ] /gete
  - [ ] /e
  - [ ] /o
  - [ ] /eventflag
  - [ ] /cooltime
  - [ ] /mount_test
  - [ ] /break_marriage
  - [ ] /open_oxevent
  - [ ] /open_oxevent_door
  - [ ] /end_oxevent
  - [ ] /end_oxevent_force
  - [ ] /start_quiz
  - [ ] /show_quiz
  - [ ] /log_oxevent
  - [ ] /get_oxevent_att
  - [ ] /give_item_to_att
  - [ ] /effect
  - [ ] /set_walk_mode
  - [ ] /set_run_mode
  - [ ] /mto
  - [ ] /mtr
  - [ ] /minfo
  - [ ] /mtax
  - [ ] /mmob
  - [ ] /mnotice
- [ ] Emoji chat/pm System (with custom emoji)
- [ ] Items
   - [ ] The Archer's Quiver (Novice, Normal, Advanced, Master)
- [ ] Marriage
- [ ] Mob Area Info
- [ ] Buy with items System
- [ ] Daily Reward System with button on MiniMap
- [ ] SwitchBot System with option to save bonuses/automatic purchase
- [ ] ignores lower buffs
- [ ] System BAN_IP
- [ ] Belt System
- [ ] Weapon Costume (on fishing rod/pickaxe)
- [ ] Pet system
  - [ ] Names
- [ ] Group Pickup
- [ ] Stack of items
- [ ] hit without weapon on horse & bow & pickaxe & rod
- [ ] Stack NPC/Magic Metal/Blessing Scroll
- [ ] Colored border on stones on weapons/armor (shard/achievement)
- [ ] Level in the negotiation window
- [ ] Penetration effect
- [ ] A + to upgrade objects with plus.
- [ ] Green Bonuses can be used on any item up to level 40
- [ ] Total Yang from private shop
- [ ] effects on all rings
- [ ] Object restrictions (you can't throw/sell/trade)
- [ ] OnDropItem
   - [ ] If the dropped object is not yours, it will have the title in red.
   - [ ] If the dropped object has at least one bonus, it will be yellow
   - [ ] Name of the book dropped on the floor appears.
- [ ] Suit Inventory
- [ ] Belts show the number of slots they unlock
- [ ] effect to Pets
- [ ] A timer for requests (friend/GROUP)
- [ ]  purple and green liquors Effects
- [ ] Ban/Unban + Reason on Ban message
- [ ] Elixirs and waters can also be stored in belt inventory
- [ ] effect on HP bar
- [ ] slow the attack bonus actually is accounted for
- [ ] waiting time between changing equipment and attacking
- [ ] prevent bosses from being pushed
- [ ] block mobs in safezone
- [ ] The offline shop
- [ ] The Mailbox system
   - [ ]  leave a message offline (containing objects/yang/only text)
- [ ] Dungeons
   - [ ] SD3
   - [ ] Dragon
   - [ ] Azrael
   - [ ] Razador
   - [ ] Temple of the Ochao
   - [ ] Meley's Lair
   - [ ] Red Dragon Fortress
   - [ ] Nemere's Watchtower
   - [ ] Enchanted Forest
   - [ ] White Dragon
   - [ ] Serpent Temple
   - [ ] Plateau of Illusions + [Time Rift & Redux Dungeons]
   - [ ] Zodiac
   - [ ] Ship defence

**Comment by MeikelLP** [comment]
@all-contriubtors add @NoFr1ends and @arves100 for code

**Comment by MeikelLP** [comment]
@all-contributors add @NoFr1ends and @arves100 for code

**Comment by MeikelLP** [comment]
@all-contributors add @arves100 for code
